In [ ]:
import pandas as pd
import os

# Path to the directory containing CSV files
folder_path = "/content/Flight"

# List to hold individual DataFrames
dataframes = []

# Loop through all CSV files in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith(".csv"):  # Only process CSV files
        file_path = os.path.join(folder_path, file_name)

        # Read the CSV file into a DataFrame
        df1 = pd.read_csv(file_path)

        # Append the DataFrame to the list
        dataframes.append(df1)

# Concatenate all DataFrames into one
df = pd.concat(dataframes, ignore_index=True)

# Display the resulting DataFrame
print(df)

                       FL_DATE OP_UNIQUE_CARRIER  OP_CARRIER_FL_NUM  \
0         6/1/2024 12:00:00 AM                9E             4824.0
1         6/1/2024 12:00:00 AM                9E             4830.0
2         6/1/2024 12:00:00 AM                9E             4830.0
3         6/1/2024 12:00:00 AM                9E             4835.0
4         6/1/2024 12:00:00 AM                9E             4874.0
...                        ...               ...                ...
5297574  2/29/2024 12:00:00 AM                YX             5840.0
5297575  2/29/2024 12:00:00 AM                YX             5841.0
5297576  2/29/2024 12:00:00 AM                YX             5841.0
5297577  2/29/2024 12:00:00 AM                YX             5842.0
5297578  2/29/2024 12:00:00 AM                YX             5844.0

         ORIGIN_AIRPORT_ID  ORIGIN_CITY_MARKET_ID ORIGIN ORIGIN_STATE_NM  \
0                    11433                  31295    DTW        Michigan
1                    11433                  31295    DTW        Michigan
2                    13459                  33459    MQT        Michigan
3                    14524                  34524    RIC        Virginia
4                    11775                  31775    FSD    South Dakota
...                    ...                    ...    ...             ...
5297574              11433                  31295    DTW        Michigan
5297575              10792                  30792    BUF        New York
5297576              12478                  31703    JFK        New York
5297577              10721                  30721    BOS   Massachusetts
5297578              12953                  31703    LGA        New York

         DEST_AIRPORT_ID  DEST_CITY_MARKET_ID DEST  ... CANCELLATION_CODE  \
0                  11042                30647  CLE  ...               NaN
1                  13459                33459  MQT  ...               NaN
2                  11433                31295  DTW  ...               NaN
3                  12953                31703  LGA  ...               NaN
4                  13487                31650  MSP  ...               NaN
...                  ...                  ...  ...  ...               ...
5297574            11066                31066  CMH  ...               NaN
5297575            12478                31703  JFK  ...               NaN
5297576            10792                30792  BUF  ...               NaN
5297577            12478                31703  JFK  ...               NaN
5297578            11278                30852  DCA  ...               NaN

         AIR_TIME  FLIGHTS  DISTANCE CARRIER_DELAY  WEATHER_DELAY  NAS_DELAY  \
0            23.0      1.0      95.0           NaN            NaN        NaN
1            57.0      1.0     349.0           NaN            NaN        NaN
2            52.0      1.0     349.0           NaN            NaN        NaN
3            47.0      1.0     292.0           NaN            NaN        NaN
4            40.0      1.0     196.0           9.0            0.0        0.0
...           ...      ...       ...           ...            ...        ...
5297574      32.0      1.0     155.0           NaN            NaN        NaN
5297575      68.0      1.0     301.0           NaN            NaN        NaN
5297576      72.0      1.0     301.0           NaN            NaN        NaN
5297577      48.0      1.0     187.0          65.0            0.0        0.0
5297578      53.0      1.0     214.0           NaN            NaN        NaN

         SECURITY_DELAY  LATE_AIRCRAFT_DELAY  OP_CARRIER_AIRLINE_ID
0                   NaN                  NaN                    NaN
1                   NaN                  NaN                    NaN
2                   NaN                  NaN                    NaN
3                   NaN                  NaN                    NaN
4                   0.0                 36.0                    NaN
...                 ...                  ...                    ...
5297574             NaN                  NaN                    NaN
5297575             NaN                  NaN                    NaN
5297576             NaN                  NaN                    NaN
5297577             0.0                  0.0                    NaN
5297578             NaN                  NaN                    NaN

[5297579 rows x 24 columns]

In [ ]:
df.isnull().sum()

FL_DATE                        0
OP_UNIQUE_CARRIER              0
OP_CARRIER_FL_NUM              1
ORIGIN_AIRPORT_ID              0
ORIGIN_CITY_MARKET_ID          0
ORIGIN                         0
ORIGIN_STATE_NM                0
DEST_AIRPORT_ID                0
DEST_CITY_MARKET_ID            0
DEST                           0
DEST_STATE_NM                  0
DEP_TIME                   80062
DEP_DELAY_NEW              80320
CANCELLED                      0
CANCELLATION_CODE        5214328
AIR_TIME                   97611
FLIGHTS                   582622
DISTANCE                       0
CARRIER_DELAY            4135579
WEATHER_DELAY            4135579
NAS_DELAY                4135579
SECURITY_DELAY           4135579
LATE_AIRCRAFT_DELAY      4135579
OP_CARRIER_AIRLINE_ID    4714957
dtype: int64

In [ ]:
import pandas as pd


# Convert to datetime format
df['FL_DATE'] = pd.to_datetime(df['FL_DATE'], format="%m/%d/%Y %I:%M:%S %p")

# Format the column to the desired format
df['FL_DATE'] = df['FL_DATE'].dt.strftime("%m/%d/%Y")

# Convert format to datetime
df['FL_DATE'] = pd.to_datetime(df['FL_DATE'], format="%m/%d/%Y")

In [ ]:
#df['FL_DATE'] = pd.to_datetime(df['FL_DATE'], format='%m/%d/%Y %I:%M:%S %p')
#df['YEAR'] = pd.to_datetime(df['YEAR'], format='%Y')
#df['MONTH'] = pd.to_datetime(df['MONTH'], format='%m')
#df['DAY_OF_MONTH'] = pd.to_datetime(df['DAY_OF_MONTH'], format='%d')
#df['DAY_OF_WEEK'] = pd.to_datetime(df['DAY_OF_WEEK']).dt.day_name()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5297579 entries, 0 to 5297578
Data columns (total 24 columns):
 #   Column                 Dtype
---  ------                 -----
 0   FL_DATE                datetime64[ns]
 1   OP_UNIQUE_CARRIER      object
 2   OP_CARRIER_FL_NUM      float64
 3   ORIGIN_AIRPORT_ID      int64
 4   ORIGIN_CITY_MARKET_ID  int64
 5   ORIGIN                 object
 6   ORIGIN_STATE_NM        object
 7   DEST_AIRPORT_ID        int64
 8   DEST_CITY_MARKET_ID    int64
 9   DEST                   object
 10  DEST_STATE_NM          object
 11  DEP_TIME               float64
 12  DEP_DELAY_NEW          float64
 13  CANCELLED              float64
 14  CANCELLATION_CODE      object
 15  AIR_TIME               float64
 16  FLIGHTS                float64
 17  DISTANCE               float64
 18  CARRIER_DELAY          float64
 19  WEATHER_DELAY          float64
 20  NAS_DELAY              float64
 21  SECURITY_DELAY         float64
 22  LATE_AIRCRAFT_DELAY    float64
 23  OP_CARRIER_AIRLINE_ID  float64
dtypes: datetime64[ns](1), float64(13), int64(4), object(6)
memory usage: 970.0+ MB

In [ ]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_CITY_MARKET_ID,DEST,...,CANCELLATION_CODE,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,OP_CARRIER_AIRLINE_ID
0,2024-06-01,9E,4824.0,11433,31295,DTW,Michigan,11042,30647,CLE,...,NaN,23.0,1.0,95.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-06-01,9E,4830.0,11433,31295,DTW,Michigan,13459,33459,MQT,...,NaN,57.0,1.0,349.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-06-01,9E,4830.0,13459,33459,MQT,Michigan,11433,31295,DTW,...,NaN,52.0,1.0,349.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-06-01,9E,4835.0,14524,34524,RIC,Virginia,12953,31703,LGA,...,NaN,47.0,1.0,292.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-06-01,9E,4874.0,11775,31775,FSD,South Dakota,13487,31650,MSP,...,NaN,40.0,1.0,196.0,9.0,0.0,0.0,0.0,36.0,NaN

In [ ]:
df.describe()

,FL_DATE,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_ID,DEST_CITY_MARKET_ID,DEP_TIME,DEP_DELAY_NEW,CANCELLED,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,OP_CARRIER_AIRLINE_ID
count,5297579,5.297578e+06,5.297579e+06,5.297579e+06,5.297579e+06,5.297579e+06,5.217517e+06,5.217259e+06,5.297579e+06,5.199968e+06,4714957.0,5.297579e+06,1.162000e+06,1.162000e+06,1.162000e+06,1.162000e+06,1.162000e+06,582622.000000
mean,2024-05-19 12:02:54.583295232,2.487307e+03,1.264810e+04,3.173371e+04,1.264810e+04,3.173372e+04,1.332669e+03,1.730967e+01,1.571491e-02,1.152510e+02,1.0,8.358346e+02,2.474390e+01,4.374669e+00,1.385351e+01,1.282040e-01,2.986898e+01,19954.620289
min,2024-01-01 00:00:00,1.000000e+00,1.013500e+04,3.007000e+04,1.013500e+04,3.007000e+04,1.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,1.0,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,19393.000000
25%,2024-03-14 00:00:00,1.144000e+03,1.129200e+04,3.064700e+04,1.129200e+04,3.064700e+04,9.080000e+02,0.000000e+00,0.000000e+00,6.400000e+01,1.0,4.000000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,19790.000000
50%,2024-05-21 00:00:00,2.208000e+03,1.288900e+04,3.145300e+04,1.288900e+04,3.145300e+04,1.326000e+03,0.000000e+00,0.000000e+00,9.800000e+01,1.0,6.820000e+02,3.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,4.000000e+00,19930.000000
75%,2024-07-26 00:00:00,3.697000e+03,1.402700e+04,3.246700e+04,1.402700e+04,3.246700e+04,1.749000e+03,1.100000e+01,0.000000e+00,1.450000e+02,1.0,1.069000e+03,2.100000e+01,0.000000e+00,1.700000e+01,0.000000e+00,3.500000e+01,20363.000000
max,2024-09-30 00:00:00,8.819000e+03,1.686900e+04,3.599100e+04,1.686900e+04,3.599100e+04,2.400000e+03,3.777000e+03,1.000000e+00,7.230000e+02,1.0,5.095000e+03,3.689000e+03,1.804000e+03,2.700000e+03,1.164000e+03,2.690000e+03,20452.000000
std,NaN,1.646358e+03,1.531815e+03,1.321276e+03,1.531812e+03,1.321281e+03,5.120837e+02,5.746260e+01,1.243702e-01,7.042657e+01,0.0,5.970341e+02,7.641331e+01,3.361466e+01,3.287057e+01,3.236521e+00,6.441235e+01,367.828848

In [ ]:
df.to_csv('flights24.csv', index=False)